### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by VictiniX888**
Might as well translate the WIP stuff as well

### CODE REVIEW

**Comment by 3TUSK** [comment]
Excuse me, but I am curious about the Chinese language file. @VictiniX888 do you speak Chinese? The whole zh_CN.lang doesn't look like made by a Chinese minecraft player.

**Comment by VictiniX888** [comment]
I've been learning Chinese for 8 years. I live in Malaysia though, but other than that, I can speak fluent Chinese.

Also it would be nice if you could tell me how it "doesn't look like made by a Chinese minecraft player"

**Comment by 3TUSK** [comment]
[line 14 and 15](https://github.com/VictiniX888/DeepResonance/blob/dadccb2a5538e8e82d4c29d283508732402e01a0/src/main/resources/assets/deepresonance/lang/zh_CN.lang#L14-L15), if the file is made by a minecraft player living in China, it is more likely to be "致密" rather than "稠密" (both words are meaning "dense", though), according to my memory.

[line 3](https://github.com/VictiniX888/DeepResonance/blob/dadccb2a5538e8e82d4c29d283508732402e01a0/src/main/resources/assets/deepresonance/lang/zh_CN.lang#L3), if I do the localization, I definitely translate it as "共振板" rather than "共振盘". I believe that translating "plate" as "板" is one of Chinese localizers' customs. You can take a look at the translation of industrialcraft2 or railcraft: everything like "**** plate" is translated to "****板".

[line 33](https://github.com/VictiniX888/DeepResonance/blob/dadccb2a5538e8e82d4c29d283508732402e01a0/src/main/resources/assets/deepresonance/lang/zh_CN.lang#L33), personally speaking, I don't think you should add an extra space, so it should be "按Shift". 

Everything else looks pretty good, as if it is made by a native speaker. Your eight years study on Chinese explains my curiousness as well as the accuracy. 
Thanks for your time to answer my question. If you have question, feel free to reply.

Beside, have you ever been to www.mcbbs.net, one of the largest minecraft forums in China?

**Comment by VictiniX888** [comment]
Ah okay, thanks for the explanation!

No, I've never been to mcbbs.net. On the Internet I usually just go to English-speaking communities. Will definitely check it out though!

**Pull request merged**
